name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm i

      - name: Run Cypress tests
        run: npm run start:headless  # Replace with your Cypress test run command

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
        if: failure()  # Upload screenshots on test failure

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos/
        if: failure()  # Upload videos on test failure
